# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(989, 640)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(30, 40, 911, 551))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.loadTButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.loadTButton.setObjectName("loadTButton")
        self.gridLayout_3.addWidget(self.loadTButton, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 2, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 1, 1, 1)
        self.drawGButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.drawGButton.setObjectName("drawGButton")
        self.gridLayout_3.addWidget(self.drawGButton, 0, 2, 1, 1)
        self.label_1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.gridLayout_3.addWidget(self.label_1, 2, 0, 1, 1)
        self.listWidget2 = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidget2.setObjectName("listWidget2")
        self.gridLayout_3.addWidget(self.listWidget2, 3, 1, 1, 1)
        self.listView = QtWidgets.QListView(self.gridLayoutWidget)
        self.listView.setObjectName("listView")
        self.gridLayout_3.addWidget(self.listView, 3, 2, 1, 1)
        self.listWidget3 = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidget3.setObjectName("listWidget3")
        self.gridLayout_3.addWidget(self.listWidget3, 1, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem, 1, 0, 1, 1)
        self.listWidget1 = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.listWidget1.setObjectName("listWidget1")
        self.gridLayout_3.addWidget(self.listWidget1, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 989, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.loadTButton.setText(_translate("MainWindow", "Load transactions"))
        self.label_2.setText(_translate("MainWindow", "Frequent sets"))
        self.label_3.setText(_translate("MainWindow", "Maximal and frequent"))
        self.drawGButton.setText(_translate("MainWindow", "Draw grid"))
        self.label_1.setText(_translate("MainWindow", "Maximal sets"))
        self.label_4.setText(_translate("MainWindow", "Transactions"))
